# Font
font_family BlexMono Nerd Font # This uses the IBM Plex Mono Nerd Font
font_size 13

# Cursor
cursor_shape block 
cursor_shape_unfocused hollow

# Background
background #101010

# Foreground
foreground #f2f2f2

##############
### Colors ###
##############

# Normal
color0 #5c5c5c
color1 #d91e58
color2 #98f329
color3 #f75806
color4 #0866ee
color5 #c72bf3
color6 #07dcc7
color7 #f2f2f2

# Blue-Grey Spectrum
color8 #5c5c5c
color9 #d91e58
color10 #98f329
color11 #f75806
color12 #0866ee
color13 #c72bf3
color14 #07dcc7
color15 #f2f2f2
